#!/bin/sh

I3_COMMAND=$1
I3_ARG=$2
INPUT_KEYSYM=$3

FOCUS_WINDOW_ID=$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')
FOCUS_WINDOW_CLASS=$(xprop -id $FOCUS_WINDOW_ID | awk '/WM_CLASS/{print $NF}' | cut -d'"' -f2)
FOCUS_PID=$(xprop -id "$FOCUS_WINDOW_ID" _NET_WM_PID | awk '{print $NF}')

has_emacs_in_tree() {
    local pid="$1"
    local children
    children=$(pgrep -P "$pid" 2>/dev/null) || return 1
    for child in $children; do
        ps -p "$child" -o comm= 2>/dev/null | grep -q 'emacs' && return 0
        has_emacs_in_tree "$child" && return 0
    done
    return 1
}

if [[ $FOCUS_WINDOW_CLASS =~ ^[Ee]macs.* ]] || has_emacs_in_tree "$FOCUS_PID"; then
    emacsclient -e "(i3-integrated-key \"$INPUT_KEYSYM\" \"$I3_COMMAND\" \"$I3_ARG\")"
else
    i3-msg "$I3_COMMAND $I3_ARG"
fi
