* Introduction

A global minor mode that integrates window movement within and outside of
~emacs~.

The program uses ~i3-msg~, ~swaymsg~, or ~aerospace~ to communicate with the
window manager.  Supported window managers: ~i3~, ~sway~ (Linux), and
~Aerospace~ (macOS).

Highlight:
- Allowing a key to be effective in both ~emacs~ and the window manager.

* Installation

** Dependencies

- ~i3~/~i3gaps~: ~xprop~
- ~sway~: ~jq~
- ~Aerospace~ (macOS): ~jq~

NOTE: to use ~i3-mode~, ~emacs~ must be running in ~server-mode~.

** Installation

- ~use-package~ and ~straight.el~:

  #+begin_src emacs-lisp
    (use-package i3-mode
      :straight (i3-mode :repo "junyi-hou/i3-mode" :host github
                         :files ("i3-mode.el" "i3-call" "sway-call" "aerospace-call"))
      :init
      (i3-mode 1))
  #+end_src

- manual installation:
  copy ~i3-mode.el~ to your ~load-path~ and ~i3-call~, ~sway-call~, or
  ~aerospace-call~ (as appropriate) to your ~PATH~, then

  #+begin_src emacs-lisp
    (require 'i3-mode)
    (i3-mode 1)
  #+end_src

* The idea

Window managers intercept key events before it can reach ~emacs~. To allow key
events go to ~emacs~, I use a simple shell script ~i3-call~/~sway-call~. It
first detect whether the focused window is an ~emacs~ window or not. If it is an
~emacs~ window, the key event is will be sent to ~emacs~.

This trick is useful if one wants to bind keys in both the window manager and
~emacs~. For example, I use ~C-<hjkl>~ to move window focus in ~emacs~. And
before this package, I use ~S-<hjkl>~ to move focus in ~i3/sway~. This is
clearly suboptimal for me, as I use two sets of keys to perform essentially the
same function. ~i3-mode~ allows me to fix this by binding ~C-<hjkl>~ in both
~i3/sway~ and ~emacs~:

#+begin_src bash
bindsym Control+l exec --no-startup-id i3-call focus right C-l
bindsym Control+h exec --no-startup-id i3-call focus left C-h
bindsym Control+k exec --no-startup-id i3-call focus up C-k
bindsym Control+j exec --no-startup-id i3-call focus down C-j
#+end_src

which instructs ~i3~ to use ~C+<hjkl>~ to move focus when the current
window is not ~emacs~. Otherwise, ~i3-call~ will pass ~C-<hjkl>~ to ~emacs~ by
calling ~emacsclient -e (i3-integrated-key "C-k" "focus" "up")~.

For ~Aerospace~ on macOS, set ~i3-flavor~ to ~aerospace~ and configure
keybindings in ~.aerospace.toml~:

#+begin_src toml
[mode.main.binding]
ctrl-l = 'exec-and-forget aerospace-call focus right C-l'
ctrl-h = 'exec-and-forget aerospace-call focus left C-h'
ctrl-k = 'exec-and-forget aerospace-call focus up C-k'
ctrl-j = 'exec-and-forget aerospace-call focus down C-j'
#+end_src

~aerospace-call~ translates the ~focus <direction>~ pair to
~aerospace focus --direction <direction>~.

* Licenses

MIT
